# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget native-bin2c native-widl native-gendib native-cabman native-fatten native-hpp native-isohybrid native-mkhive native-mkisofs native-obj2bin native-spec2def native-geninc native-mkshelllink native-utf16le native-xml2sdb native-rsym native-pefixup)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target native-bin2c
add_executable(native-bin2c IMPORTED)

# Create imported target native-widl
add_executable(native-widl IMPORTED)

# Create imported target native-gendib
add_executable(native-gendib IMPORTED)

# Create imported target native-cabman
add_executable(native-cabman IMPORTED)

# Create imported target native-fatten
add_executable(native-fatten IMPORTED)

# Create imported target native-hpp
add_executable(native-hpp IMPORTED)

# Create imported target native-isohybrid
add_executable(native-isohybrid IMPORTED)

# Create imported target native-mkhive
add_executable(native-mkhive IMPORTED)

# Create imported target native-mkisofs
add_executable(native-mkisofs IMPORTED)

# Create imported target native-obj2bin
add_executable(native-obj2bin IMPORTED)

# Create imported target native-spec2def
add_executable(native-spec2def IMPORTED)

# Create imported target native-geninc
add_executable(native-geninc IMPORTED)

# Create imported target native-mkshelllink
add_executable(native-mkshelllink IMPORTED)

# Create imported target native-utf16le
add_executable(native-utf16le IMPORTED)

# Create imported target native-xml2sdb
add_executable(native-xml2sdb IMPORTED)

# Create imported target native-rsym
add_executable(native-rsym IMPORTED)

# Create imported target native-pefixup
add_executable(native-pefixup IMPORTED)

# Import target "native-bin2c" for configuration ""
set_property(TARGET native-bin2c APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-bin2c PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/bin2c.exe"
  )

# Import target "native-widl" for configuration ""
set_property(TARGET native-widl APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-widl PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/widl.exe"
  )

# Import target "native-gendib" for configuration ""
set_property(TARGET native-gendib APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-gendib PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/gendib.exe"
  )

# Import target "native-cabman" for configuration ""
set_property(TARGET native-cabman APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-cabman PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/cabman.exe"
  )

# Import target "native-fatten" for configuration ""
set_property(TARGET native-fatten APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-fatten PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/fatten.exe"
  )

# Import target "native-hpp" for configuration ""
set_property(TARGET native-hpp APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-hpp PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/hpp.exe"
  )

# Import target "native-isohybrid" for configuration ""
set_property(TARGET native-isohybrid APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-isohybrid PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/isohybrid.exe"
  )

# Import target "native-mkhive" for configuration ""
set_property(TARGET native-mkhive APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-mkhive PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/mkhive.exe"
  )

# Import target "native-mkisofs" for configuration ""
set_property(TARGET native-mkisofs APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-mkisofs PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/mkisofs.exe"
  )

# Import target "native-obj2bin" for configuration ""
set_property(TARGET native-obj2bin APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-obj2bin PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/obj2bin.exe"
  )

# Import target "native-spec2def" for configuration ""
set_property(TARGET native-spec2def APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-spec2def PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/spec2def.exe"
  )

# Import target "native-geninc" for configuration ""
set_property(TARGET native-geninc APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-geninc PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/geninc.exe"
  )

# Import target "native-mkshelllink" for configuration ""
set_property(TARGET native-mkshelllink APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-mkshelllink PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/mkshelllink.exe"
  )

# Import target "native-utf16le" for configuration ""
set_property(TARGET native-utf16le APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-utf16le PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/utf16le.exe"
  )

# Import target "native-xml2sdb" for configuration ""
set_property(TARGET native-xml2sdb APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-xml2sdb PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/xml2sdb.exe"
  )

# Import target "native-rsym" for configuration ""
set_property(TARGET native-rsym APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-rsym PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/rsym.exe"
  )

# Import target "native-pefixup" for configuration ""
set_property(TARGET native-pefixup APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(native-pefixup PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "E:/github/reactos/host-tools/pefixup.exe"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
